routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::group(['middleware' => ['auth']], function () {
    Route::get('/', ['as' => 'dashboard', 'uses' => 'PagesController@dashboard']);
//    Route::get('logout', ['as' => 'logout', 'uses' => 'Authentication\AuthController@logout']);
    Route::get('user-profile', ['as' => 'user.profile', 'uses' => 'UsersController@profile']);
    Route::post('user-profile', ['as' => 'user.profile.update', 'uses' => 'UsersController@postProfile']);
    Route::resource('profile', 'CompanyProfileController');
    Route::resource('departments', 'DepartmentsController');
    Route::get('department-print/{department}', ['as' => 'departments.generate', 'uses' => 'DepartmentsController@generate']);
    Route::post('department-print', ['as' => 'departments.pdfs', 'uses' => 'DepartmentsController@getPDF']);
    Route::resource('allowances', 'AllowancesController');
    Route::resource('employee-allowances', 'EmployeeAllowancesController');
    Route::get('allowances-print/{id}', ['as' => 'allowances.generate', 'uses' => 'AllowancesController@generate']);
    Route::post('allowances-print', ['as' => 'allowances.document', 'uses' => 'AllowancesController@getDocument']);
    Route::resource('deductions', 'DeductionsController');
    Route::resource('employee-deductions', 'EmployeeDeductionsController');
    Route::get('deductions-report/{id}', ['as' => 'deductions.report', 'uses' => 'DeductionsController@report']);
    Route::post('deductions-print/{id}', ['as' => 'deductions.generate', 'uses' => 'DeductionsController@generate']);
    Route::post('deductions-print', ['as' => 'deductions.document', 'uses' => 'DeductionsController@getDocument']);
    Route::resource('reliefs', 'ReliefController');
    Route::resource('employee-types', 'EmployeeTypesController');
    Route::resource('payment-methods', 'PaymentMethodsController');
    Route::resource('payment-structures', 'PaymentStructureController');
    Route::resource('shifts', 'ShiftsController');
    Route::resource('work-plans', 'WorkPlanController');
    Route::resource('grades', 'PayGradesController');
    Route::resource('holidays', 'HolidaysController');
    Route::resource('employees', 'EmployeesController');
    Route::resource('contracts', 'EmployeeContractsController');
    Route::resource('assignments', 'EmployeeAssignmentsController');
    Route::resource('employee-payment-methods', 'EmployeePaymentMethodsController');
    Route::resource('payroll', 'PayrollController');
    Route::get('finalize-payroll', 'PayrollController@finalize');
    Route::get('delete-payroll', 'PayrollController@deletePayrolls');
    Route::get('payroll-pdf/{id}', ['as' => 'payroll.pdf', 'uses' => 'PayrollController@getPDF']);
    Route::get('payroll-pdfs', ['as' => 'payroll.pdfs', 'uses' => 'PayrollController@getAllPDFs']);
    Route::get('payroll-view/{month}', ['as' => 'payroll.show.all', 'uses' => 'PayrollController@viewAll']);
    Route::get('payroll-report', ['as' => 'payroll.report', 'uses' => 'PayrollController@report']);
    Route::post('payroll-generate', ['as' => 'payroll.generate', 'uses' => 'PayrollController@generate']);
    Route::post('payroll-print', ['as' => 'payroll.document', 'uses' => 'PayrollController@getDocument']);
    Route::resource('advances', 'AdvancesController');
    Route::get('advances-bulk', ['as' => 'advances.bulk', 'uses' => 'AdvancesController@bulkAssign']);
    Route::post('advances-bulk', ['as' => 'advances.process', 'uses' => 'AdvancesController@bulkProcess']);
    Route::get('loans/details/{loanId}', ['as' => 'loans.details', 'uses' => 'LoansController@details']);
    Route::resource('loans', 'LoansController');
    Route::resource('policies', 'PoliciesController');
//    Route::resource('tax', 'TaxReportsController');
    Route::get('tax', ['as' => 'tax.index', 'uses' => 'TaxReportsController@index']);
    Route::get('tax-report', 'TaxReportsController@getYear');
    Route::post('tax/{type}', ['as' => 'tax.show', 'uses' => 'TaxReportsController@getReport']);
    Route::resource('template', 'ReportTemplateController');
    Route::resource('worked', 'DaysWorkedController');
    Route::resource('hours-worked', 'HoursWorkedController');
    Route::resource('units-made', 'UnitsMadeController');
    Route::resource('coinage', 'CoinageController');
    Route::resource('users', 'UsersController');
    Route::resource('api', 'APIController');
    Route::get('allowance-report', 'ReportsController@allowances')->name('allowance-report');
});

//
//Route::get('login', ['as' => 'login.index', 'uses' => 'Auth\LoginController@getLogin']);
//Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@getLogin']);
//
//Route::post('login', ['as' => 'login.store', 'uses' => 'Auth\LoginController@postLogin']);
//Route::get('forgot', ['as' => 'forgot.index', 'uses' => 'Auth\LoginController@index']);
//Route::post('forgot', ['as' => 'forgot.store', 'uses' => 'Auth\LoginController@index']);


// Route::post('login', 'Auth\LoginController@login')->middleware('throttle:5,1');

app/Http/Controllers/HolidaysController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\HolidayRequests;
use App\Policies\Policy;
use Illuminate\Http\Request;

use App\Http\Requests;
use Payroll\Models\Holiday;

class HolidaysController extends Controller
{
    /**
     * @var Holiday
     */
    private $holiday;

    /**
     * HolidaysController constructor.
     *
     * @param Holiday $holiday
     */
    public function __construct(Holiday $holiday)
    {
        $this->holiday = $holiday;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Policy::canRead(new Holiday());

        return view('modules.structures.holidays.index')
            ->withHolidays($this->holiday->all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        Policy::canCreate(new Holiday());

        return view('modules.structures.holidays.create')
            ->withHolidays($this->holiday->all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  HolidayRequests  $request
     * @return \Illuminate\Http\Response
     */
    public function store(HolidayRequests $request)
    {
        Policy::canCreate(new Holiday());

        $this->holiday->create($request->all());
        flash('Successfully added a holiday', 'success');

        return redirect()->route('holidays.create');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        Policy::canUpdate(new Holiday());

        $holiday = $this->holiday->findOrFail($id);

        return view('modules.structures.holidays.edit')
            ->withHoliday($holiday);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Policy::canUpdate(new Holiday());

        $holiday = $this->holiday->findOrFail($id);
        $holiday->name = $request->get('name');
        $holiday->save();
        flash('Successfully edited holiday.', 'success');

        return redirect()->route('holidays.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Policy::canDelete(new Holiday());

        $holiday = $this->holiday->findOrFail($id);
        $holiday->delete();
        flash('Successfully deleted holiday.', 'success');

        return redirect()->route('holidays.index');
    }
}

resources/views/modules/structures/holidays/create.blade.php
<!-- resources/views/modules/structures/holidays/create.blade.php -->
@extends('layout')

@section('content')
    <div class="page-head">
        <div class="page-title">
            <h1>Holidays - <small> Set up the days that are considered holidays within the organization</small></h1>
        </div>
    </div>
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="{{ url('/') }}">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="{{ route('holidays.index') }}">Holidays</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="#">Create</a>
        </li>
    </ul>

    <div class="row">
        <div class="col-sm-12">
                <div class="portlet light">
                    <div class="portlet-title">
                        <div class="caption font-red-sunglo">
                            <i class="fa fa-briefcase font-red-sunglo"></i>
                            <span class="caption-subject bold uppercase"> Holiday Details</span>
                        </div>
                    </div>
                    <div class="portlet-body form">
                        <div class="form-body">
                            <div class="calendar"></div>
                            <div class="form-group form-md-line-input form-md-floating-label">
                                <a class="btn btn-danger" href="{{ route('holidays.index') }}">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    </div>

    <div class="modal fade bs-modal-sm" id="addEvent" tabindex="-1" role="dialog" aria-hidden="true" style="position: fixed; top: 30% !important;">
        <div class="modal-dialog modal-sm">
            <form action="{{ route('holidays.store') }}" method="post" role="form">
                {{ csrf_field() }}
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                        <h4 class="modal-title">Holiday Details</h4>
                    </div>
                    <div class="modal-body">
                        <label for="event_name">Holiday Name</label>
                        <input type="text" id="event_name" class="form-control" name="name" required>
                        <input type="hidden" name="holiday_date" id="holiday_date">
                        <input type="hidden" name="holiday_day" id="holiday_day">
                        <input type="hidden" name="holiday_week" id="holiday_week">
                        <input type="hidden" name="holiday_month" id="holiday_month">
                        <input type="hidden" name="holiday_year" id="holiday_year">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn blue" id="saveEvent">Save changes</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

@endsection

@section('footer')
    <script>
        $(document).ready(function() {
            // Initialize FullCalendar
            $('.calendar').fullCalendar({
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'month,basicWeek'
                },
                defaultDate: '{{ \Carbon\Carbon::now()->toDateString() }}',
                editable: true,
                eventLimit: true,
                events: [
                    @foreach($holidays as $holiday)
                    {
                        allDay: true,
                        id: {{ $holiday->id }},
                        title: '{{ addslashes($holiday->name) }}',
                        start: '{{ Carbon\Carbon::now()->year . '-' . $holiday->holiday_month . '-' . $holiday->holiday_day }}'
                    },
                    @endforeach
                ],
                dayClick: function(date) {
                    // Get the selected date in 'YYYY-MM-DD' format
                    var eventDate = date.format('YYYY-MM-DD');  
                    var eYear = date.year();                   // Year (e.g., 2024)
                    var eMonth = date.format('MM');            // Month (as two-digit string)
                    var eDateDay = date.format('DD');         // Day (as two-digit string)
                    var eWeek = date.isoWeek();               // ISO week number

                    // Populate modal fields with the extracted date values
                    $('#holiday_date').val(eventDate);         // Full date (e.g., 2024-06-12)
                    $('#holiday_day').val(eDateDay);         // Day of the month (e.g., 12)
                    $('#holiday_week').val(eWeek);            // ISO week number (e.g., 24)
                    $('#holiday_month').val(eMonth);         // Month as two-digit string
                    $('#holiday_year').val(eYear);           // Year (e.g., 2024)

                    // Show the modal
                    $('#addEvent').modal('show');
                }
            });

            // Hover effect on calendar days
            $('.calendar').on('mouseenter', '.fc-day', function() {
                $(this).html('<br><p style="padding:10px;">Click to<br>add holiday</p>');
            }).on('mouseleave', '.fc-day', function() {
                $(this).html(''); // Clear hover content
            });
        });
    </script>
@endsection


Whoops, looks like something went wrong.
(2/2) ErrorException

Call to undefined function now() (View: /var/www/html/cloudwage/resources/views/modules/structures/holidays/create.blade.php)

resources/views/modules/structures/holidays/edit.blade.php
@extends('layout')
@section('content')
    <div class="page-head">
        <div class="page-title">
            <h1>Holidays - <small> Set up the days that are considered holidays within the organization</small></h1>
        </div>
    </div>
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="{{ url('/') }}">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="{{ route('holidays.index') }}">Holidays</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="#">Edit</a>
        </li>
    </ul>

    <div class="row">
        <div class="col-sm-12">
            <form action="{{ route('holidays.update', $holiday->id) }}" method="post" role="form">
                {{ csrf_field() }}
                {{ method_field('put') }}
                <div class="portlet light">
                    <div class="portlet-title">
                        <div class="caption font-red-sunglo">
                            <i class="fa fa-briefcase font-red-sunglo"></i>
                            <span class="caption-subject bold uppercase"> Holiday Details</span>
                        </div>
                    </div>
                    <div class="portlet-body form">
                        <div class="form-body">
                            <div class="form-group form-md-line-input form-md-floating-label">
                                <input type="text" class="form-control" id="name" name="name" value="{{ $holiday->name or old('name') }}" required>
                                <label for="name">Holiday Name* (e.g. Group A)</label>
                                <span class="help-block">This is the name of the holiday</span>
                            </div>

                        <div class="form-group form-md-line-input form-md-floating-label">
                                <input type="submit" class="btn btn-primary" value="Save">
                                <a class="btn btn-danger" href="{{ route('holidays.index') }}">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/modules/structures/holidays/index.blade.php
@extends('layout')

@section('content')
    <?php $months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'] ?>
    <div class="page-head">
        <div class="page-title">
            <h1>Holidays - <small> Set up the days that are considered holidays within the organization</small></h1>
        </div>
    </div>
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="{{ url('/') }}">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="{{ route('holidays.index') }}">Holidays</a>
        </li>
    </ul>

    <div class="row">
        <div class="col-sm-12">
            <!-- BEGIN PORTLET-->
            <div class="portlet light ">
                <div class="portlet-title">
                    <div class="caption caption-md">
                        <i class="icon-bar-chart theme-font-color hide"></i>
                        <span class="caption-subject theme-font-color bold uppercase">Current Holidays</span>
                    </div>
                    <div class="actions">
                        <a href="{{ route('holidays.create') }}" class="btn btn-transparent grey-salsa btn-circle btn-sm active"><i class="fa fa-plus"></i> Add Holiday</a>
                    </div>
                </div>
                <div class="portlet-body">
                    <table class="table table-striped table-hover table-responsive dataTable">
                        <thead>
                            <tr>
                                <th>
                                    Name
                                </th>
                                <th>
                                    Day
                                </th>
                                <th>
                                    Month
                                </th>
                                <th>
                                    Edit
                                </th>
                                <th>
                                    Delete
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($holidays as $holiday)
                            <tr>
                                <td>
                                    {{ $holiday->name }}
                                </td>
                                <td>
                                    {{ $holiday->holiday_day }}
                                </td>
                                <td>
                                    {{ $months[$holiday->holiday_month - 1] }}
                                </td>
                                <td>
                                    <a class="btn btn-success btn-xs" href="{{ route('holidays.edit', $holiday->id) }}">
                                        Edit </a>
                                </td>
                                <td>
                                    <a href="{{ route('holidays.destroy', $holiday->id) }}" class="btn btn-danger btn-xs" data-method="delete" rel="nofollow" data-confirm="Are you sure you want to delete this?" data-token="{{ csrf_token() }}">Delete</a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END PORTLET-->
        </div>
    </div>

@endsection

resources/views/modules/structures/holidays/show.blade.php
@extends('layout')
@section('content')
    <div class="page-head">
        <div class="page-title">
            <h1>Pay Grades - <small> Set up the pay grades that will be assigned within the organization</small></h1>
        </div>
    </div>
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="{{ url('/') }}">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="{{ route('grades.index') }}">Pay Grades</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="#">View</a>
        </li>
    </ul>

    <div class="row">
        <div class="col-sm-12">
                <div class="portlet light">
                    <div class="portlet-title">
                        <div class="caption font-red-sunglo">
                            <i class="fa fa-briefcase font-red-sunglo"></i>
                            <span class="caption-subject bold uppercase"> Pay Grade Details</span>
                        </div>
                    </div>
                    <div class="portlet-body form">
                        <div class="form-body row">
                            <div class="col-sm-6">
                                <div class="form-group form-md-line-input form-md-floating-label">
                                    <label for="name">Pay Grade Name</label>
                                    <div class="form-control">{{ $grade->name }}</div>
                                </div>
                                <div class="form-group form-md-line-input form-md-floating-label">
                                    <label for="name">Currency</label>
                                    <div class="form-control">{{ $grade->currency->name }}</div>
                                </div>
                                <div class="form-group form-md-line-input form-md-floating-label">
                                    <label for="name">Basic Salary</label>
                                    <div class="form-control">{{ $grade->currency->code .' ' . number_format($grade->basic_salary, 2) }}</div>
                                </div>
                                <div class="form-group form-md-line-input form-md-floating-label">
                                    <label for="name">Annual Increment</label>
                                    <div class="form-control">{{ $grade->annual_increment }}</div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                @if($grade->default_allowances)
                                <div class="form-group form-md-line-input form-md-floating-label">
                                    <label for="name">Default Allowances</label>
                                    <?php $allowances = explode(",", $grade->default_allowances); ?>
                                    @foreach($allowances as $allowance)
                                    <div class="form-control"><a href="{{ route('allowances.show', $allowance) }}">{{ Payroll\Models\Allowance::findOrFail($allowance)->name }}</a></div>
                                    @endforeach
                                </div>
                                @endif
                                @if($grade->default_deductions)
                                    <div class="form-group form-md-line-input form-md-floating-label">
                                        <label for="name">Default Deductions</label>
                                        <?php $deductions = explode(",", $grade->default_deductions); ?>
                                        @foreach($deductions as $deduction)
                                            <div class="form-control"><a href="{{ route('deductions.show', $deduction) }}">{{ Payroll\Models\Deduction::findOrFail($deduction)->name }}</a></div>
                                        @endforeach
                                    </div>
                                @endif
                                
                                <div class="form-group form-md-line-input form-md-floating-label">
                                    <a class="btn btn-success" href="{{ route('grades.edit', $grade->id) }}">Edit</a>
                                    <a href="{{ route('grades.destroy', $grade->id) }}" class="btn btn-danger" data-method="delete" rel="nofollow" data-confirm="Are you sure you want to delete this?" data-token="{{ csrf_token() }}">Delete</a>
                                    <a class="btn btn-warning" href="{{ URL::previous() }}">Back</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    </div>
@endsection