routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::group(['middleware' => ['auth']], function () {
    Route::get('/', ['as' => 'dashboard', 'uses' => 'PagesController@dashboard']);
//    Route::get('logout', ['as' => 'logout', 'uses' => 'Authentication\AuthController@logout']);
    Route::get('user-profile', ['as' => 'user.profile', 'uses' => 'UsersController@profile']);
    Route::post('user-profile', ['as' => 'user.profile.update', 'uses' => 'UsersController@postProfile']);
    Route::resource('profile', 'CompanyProfileController');
    Route::resource('departments', 'DepartmentsController');
    Route::get('department-print/{department}', ['as' => 'departments.generate', 'uses' => 'DepartmentsController@generate']);
    Route::post('department-print', ['as' => 'departments.pdfs', 'uses' => 'DepartmentsController@getPDF']);
    Route::resource('allowances', 'AllowancesController');
    Route::resource('employee-allowances', 'EmployeeAllowancesController');
    Route::get('allowances-print/{id}', ['as' => 'allowances.generate', 'uses' => 'AllowancesController@generate']);
    Route::post('allowances-print', ['as' => 'allowances.document', 'uses' => 'AllowancesController@getDocument']);
    Route::resource('deductions', 'DeductionsController');
    Route::resource('employee-deductions', 'EmployeeDeductionsController');
    Route::get('deductions-report/{id}', ['as' => 'deductions.report', 'uses' => 'DeductionsController@report']);
    Route::post('deductions-print/{id}', ['as' => 'deductions.generate', 'uses' => 'DeductionsController@generate']);
    Route::post('deductions-print', ['as' => 'deductions.document', 'uses' => 'DeductionsController@getDocument']);
    Route::resource('reliefs', 'ReliefController');
    Route::resource('employee-types', 'EmployeeTypesController');
    Route::resource('payment-methods', 'PaymentMethodsController');
    Route::resource('payment-structures', 'PaymentStructureController');
    Route::resource('shifts', 'ShiftsController');
    Route::resource('work-plans', 'WorkPlanController');
    Route::resource('grades', 'PayGradesController');
    Route::resource('holidays', 'HolidaysController');
    Route::resource('employees', 'EmployeesController');
    Route::resource('contracts', 'EmployeeContractsController');
    Route::resource('assignments', 'EmployeeAssignmentsController');
    Route::resource('employee-payment-methods', 'EmployeePaymentMethodsController');
    Route::resource('payroll', 'PayrollController');
    Route::get('finalize-payroll', 'PayrollController@finalize');
    Route::get('delete-payroll', 'PayrollController@deletePayrolls');
    Route::get('payroll-pdf/{id}', ['as' => 'payroll.pdf', 'uses' => 'PayrollController@getPDF']);
    Route::get('payroll-pdfs', ['as' => 'payroll.pdfs', 'uses' => 'PayrollController@getAllPDFs']);
    Route::get('payroll-view/{month}', ['as' => 'payroll.show.all', 'uses' => 'PayrollController@viewAll']);
    Route::get('payroll-report', ['as' => 'payroll.report', 'uses' => 'PayrollController@report']);
    Route::post('payroll-generate', ['as' => 'payroll.generate', 'uses' => 'PayrollController@generate']);
    Route::post('payroll-print', ['as' => 'payroll.document', 'uses' => 'PayrollController@getDocument']);
    Route::resource('advances', 'AdvancesController');
    Route::get('advances-bulk', ['as' => 'advances.bulk', 'uses' => 'AdvancesController@bulkAssign']);
    Route::post('advances-bulk', ['as' => 'advances.process', 'uses' => 'AdvancesController@bulkProcess']);
    Route::get('loans/details/{loanId}', ['as' => 'loans.details', 'uses' => 'LoansController@details']);
    Route::resource('loans', 'LoansController');
    Route::resource('policies', 'PoliciesController');
//    Route::resource('tax', 'TaxReportsController');
    Route::get('tax', ['as' => 'tax.index', 'uses' => 'TaxReportsController@index']);
    Route::get('tax-report', 'TaxReportsController@getYear');
    Route::post('tax/{type}', ['as' => 'tax.show', 'uses' => 'TaxReportsController@getReport']);
    Route::resource('template', 'ReportTemplateController');
    Route::resource('worked', 'DaysWorkedController');
    Route::resource('hours-worked', 'HoursWorkedController');
    Route::resource('units-made', 'UnitsMadeController');
    Route::resource('coinage', 'CoinageController');
    Route::resource('users', 'UsersController');
    Route::resource('api', 'APIController');
    Route::get('allowance-report', 'ReportsController@allowances')->name('allowance-report');
});

//
//Route::get('login', ['as' => 'login.index', 'uses' => 'Auth\LoginController@getLogin']);
//Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@getLogin']);
//
//Route::post('login', ['as' => 'login.store', 'uses' => 'Auth\LoginController@postLogin']);
//Route::get('forgot', ['as' => 'forgot.index', 'uses' => 'Auth\LoginController@index']);
//Route::post('forgot', ['as' => 'forgot.store', 'uses' => 'Auth\LoginController@index']);


// Route::post('login', 'Auth\LoginController@login')->middleware('throttle:5,1');

app/Http/Controllers/AllowancesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Requests\AllowanceRequest;
use App\Http\Requests\ReportRequest;
use App\Policies\Policy;
use Illuminate\Http\Request;
use Payroll\Models\Allowance;
use Payroll\Models\CompanyProfile;
use Payroll\Models\Employee;
use Payroll\Models\EmployeeAllowance;
use Payroll\Models\Relief;
use Payroll\Parsers\DocumentGenerator;
use Schema;

class AllowancesController extends Controller
{
    protected $allowances;

    protected $relief;

    /**
     * AllowancesController constructor.
     *
     * @param Allowance $allowances
     * @param Relief    $relief
     */
    public function __construct(Allowance $allowances, Relief $relief)
    {
        $this->allowances = $allowances;
        $this->relief = $relief;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Policy::canRead(new Allowance());

        return view('modules.company.allowances.index')
            ->withAllowances($this->allowances->all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        Policy::canCreate(new Allowance());
        $defaultCurr = CompanyProfile::first()->currency_id;

        return view('modules.company.allowances.create')
            ->withDefaultCurrency($defaultCurr);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param AllowanceRequest $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     */
    public function store(AllowanceRequest $request)
    {
        Policy::canCreate(new Allowance());
        if (! $this->validateRelief($request)) {
            return redirect()->back()
                ->withInput()
                ->withErrors(['message' => 'Please enter the relief details']);
        }

        Allowance::create($request->all());

        flash('Successfully added new allowance.', 'success');

        return redirect()->route('allowances.index');
    }

    public function show($id)
    {
        Policy::canRead(new Allowance());
        $allowance = Allowance::with(['employees', 'employeeAllowances', 'relief'])
            ->findOrFail($id);

        return view('modules.company.allowances.show')
            ->withAllowance($allowance)
            ->withEmployees($allowance->employees);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        Policy::canUpdate(new Allowance());
        $allowance = Allowance::with(['relief'])->findOrFail($id);

        return view('modules.company.allowances.edit')
            ->withAllowance($allowance);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param AllowanceRequest $request
     * @param                  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     * @internal param int $id
     */
    public function update(AllowanceRequest $request, $id)
    {
        Policy::canUpdate(new Allowance());
        if (! $this->validateRelief($request)) {
            return redirect()->back()
                ->withInput()
                ->withErrors(['message' => 'Please enter the relief details']);
        }

        Allowance::findOrFail($id)->update($request->all());

        flash('Successfully updated allowance', 'success');

        return redirect()->route('allowances.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Policy::canDelete(new Allowance());
        $allowance = Allowance::findOrFail($id);
        if ($allowance->has_relief == 1) {
            Relief::where('reliefable_id', $id)
                ->where('reliefable_type', 'Allowance')->delete();
        }

        $allowance->employeeAllowances()->delete();
        $allowance->delete();

        flash('Successfully deleted allowance', 'success');

        return redirect()->route('allowances.index');
    }

    public function generate($id, DocumentGenerator $generator)
    {
        Policy::canRead(new Allowance());

        return $generator->withModuleId(Allowance::MODULE_ID)
            ->setColumns($this->getColumns())
            ->withFormAction(route('allowances.document'))
            ->withItemId($id)
            ->view();
    }

    private function getColumns()
    {
        $columns = collect();
        foreach (Schema::getColumnListing((new Allowance())->getTable()) as $column) {
            if ($column == 'created_at' ||
                $column == 'updated_at' ||
                $column == 'deleted_at' ||
                $column == 'currency_id' ||
                $column == 'id'
            ) {
                continue;
            }

            $columns->push($column);
        }

        foreach (Schema::getColumnListing((new EmployeeAllowance())->getTable()) as $column) {
            if ($column == 'created_at' ||
                $column == 'updated_at' ||
                $column == 'deleted_at' ||
                $column == 'id' ||
                $column == 'employee_id' ||
                $column == 'currency_id' ||
                $column == 'allowance_id'
            ) {
                continue;
            }

            $columns->push($column);
        }

        foreach (Schema::getColumnListing((new Employee())->getTable()) as $column) {
            if ($column == 'created_at' ||
                $column == 'updated_at' ||
                $column == 'deleted_at' ||
                $column == 'id' ||
                $column == 'employee_id' ||
                $column == 'currency_id' ||
                $column == 'allowance_id'
            ) {
                continue;
            }

            $columns->push($column);
        }

        return $columns->sort();
    }

    public function getDocument(ReportRequest $request, DocumentGenerator $generator)
    {
        Policy::canRead(new Allowance());
        $allowance = $this->allowances->with(['employees', 'employeeAllowances'])->findOrFail($request->get('item_id'));
        $employeeAllowances = $allowance->employeeAllowances->keyBy('employee_id');

        $rows = collect();
        foreach ($allowance->employees as $employee) {
            foreach ($employeeAllowances->get($employee->id)->toArray() as $key => $value) {
                $employee->$key = $value;
            }
            foreach ($allowance->toArray() as $key => $value) {
                $employee->$key = $value;
            }

            $rows->push($employee);
        }

        $generator = $generator->prepare($request);
        $document = $generator->withRows($rows)
            ->render();

        return $document;
    }

    private function validateRelief(Request $request)
    {
        if ($request->get('has_relief')) {
            if (! $request->has('relief_name') || ! $request->has('relief_amount')) {
                return false;
            }
        }

        return true;
    }
}

resources/views/modules/company/allowances/index.blade.php
@extends('layout')

@section('content')
    <div class="page-head">
        <div class="page-title">
            <h1>Allowances - <small> Set up the allowances that can be given to employees in the organization</small></h1>
        </div>
    </div>
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="{{ url('/') }}">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="{{ route('allowances.index') }}">Allowances</a>
        </li>
    </ul>

    <div class="row">
        <div class="col-sm-12">
            <!-- BEGIN PORTLET-->
            <div class="portlet light ">
                <div class="portlet-title">
                    <div class="caption caption-md">
                        <i class="icon-bar-chart theme-font-color hide"></i>
                        <span class="caption-subject theme-font-color bold uppercase">Current Allowances</span>
                    </div>
                    <div class="actions">
                        <a href="{{ route('allowances.create') }}" class="btn btn-transparent grey-salsa btn-circle btn-sm active"><i class="fa fa-plus"></i> Add Allowance</a>
                    </div>
                </div>
                <div class="portlet-body">
                    <table class="table table-striped table-hover table-responsive dataTable" id="allowances_table">
                        <thead>
                            <tr>
                                <th>
                                    Name
                                </th>
                                <th>
                                    Type
                                </th>
                                <th>
                                    Rate
                                </th>
                                <th>
                                    Has Relief?
                                </th>
                                <th>
                                    Taxable
                                </th>
                                <th>
                                    Edit
                                </th>
                                <th>
                                    Delete
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($allowances as $allowance)
                            <tr>
                                <td>
                                    <a href="{{ route('allowances.show', ['id' => $allowance->id]) }}">{{ $allowance->name }}</a>
                                </td>
                                <td class="text-right">
                                    {{ $allowance->type == 'rate' ? 'Fixed Rate' : 'Per Employee' }}
                                </td>
                                <td class="text-right">
                                    {{ $allowance->rate }}
                                </td>
                                <td class="text-center">
                                    {{ $allowance->has_relief == 1 ? 'Yes' : 'No' }}
                                </td>
                                <td class="text-center">
                                    {{ $allowance->taxable == 1 ? 'Yes' : 'No' }}
                                </td>
                                <td class="text-center">
                                    <a class="btn btn-success btn-xs" href="{{ route('allowances.edit', ['allowances' => $allowance->id]) }}">
                                        Edit </a>
                                </td>
                                <td class="text-center">
                                    @if(! $allowance->system_install)
                                        <a href="{{ route('allowances.destroy', $allowance->id) }}" class="btn btn-danger btn-xs" data-method="delete" rel="nofollow" data-confirm="Are you sure you want to delete this?" data-token="{{ csrf_token() }}">Delete</a>
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END PORTLET-->
        </div>
    </div>

@endsection

resources/views/modules/company/allowances/show.blade.php
@extends('layout')
@section('content')
    <div class="page-head">
        <div class="page-title">
            <h1>Allowances - <small> View an allowance and its details</small></h1>
        </div>
    </div>
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="{{ url('/') }}">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="{{ route('allowances.index') }}">Allowances</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="#">View</a>
        </li>
    </ul>

    <div class="row">
        <div class="col-sm-12">
            <div class="portlet box blue">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-user"></i>{{ $allowance->name }} Details
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="tabbable-custom nav-justified">
                        <ul class="nav nav-tabs nav-justified">
                            <li class="active">
                                <a href="#details" data-toggle="tab">
                                    Allowance Details </a>
                            </li>
                            <li>
                                <a href="#employees" data-toggle="tab">
                                    Employees with {{ $allowance->name }} </a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="details">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div>
                                            <div><strong>Allowance Name</strong></div>
                                            <p>{{ $allowance->name }}</p>
                                            <hr>
                                        </div>
                                        <div>
                                            <div><strong>Currency</strong></div>
                                            <p>{{ $allowance->currency->name }}</p>
                                            <hr>
                                        </div>
                                        <div>
                                            <div><strong>Allocation Type</strong></div>
                                            <p>{{ $allowance->type == 'rate' ? "Rate on basic pay" : "Per Employee" }}</p>
                                            <hr>
                                        </div>
                                        <div>
                                            <div><strong>Allowance Type</strong></div>
                                            <p>{{ $allowance->non_cash == 1 ? "Non-Cash Benefit" : "Cash Benefit" }}</p>
                                            <hr>
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div>
                                            <div><strong>Payment Allocation</strong></div>
                                            <p>{{ $allowance->in_basic == 1 ? "Included in basic pay" : "Excluded in basic pay" }}</p>
                                            <hr>
                                        </div>
                                        <div>
                                            <div><strong>Taxable?</strong></div>
                                            <p>{{ $allowance->taxable == 1 ? "Yes" : "No" }}</p>
                                            <hr>
                                        </div>
                                        @if($allowance->taxable)
                                            <div>
                                                <div><strong>Tax Rate</strong></div>
                                                <p>{{ $allowance->tax_rate }}%</p>
                                                <hr>
                                            </div>
                                        @endif
                                        <div>
                                            <div><strong>Has Relief?</strong></div>
                                            <p>{{ $allowance->has_relief == 1 ? 'Yes' : 'No' }}</p>
                                            <hr>
                                        </div>

                                        @if($allowance->has_relief)
                                            <div>
                                                <div><strong>Relief Name</strong></div>
                                                <p>{{ $allowance->relief->name }}</p>
                                                <hr>
                                            </div>
                                            <div>
                                                <div><strong>Relief Amount</strong></div>
                                                <p>{{ $allowance->relief->amount }}</p>
                                                <hr>
                                            </div>
                                        @endif

                                        <div>
                                            <a class="btn btn-success" href="{{ route('allowances.edit', ['allowances' => $allowance->id]) }}">Edit</a>
                                            <a href="{{ route('allowances.destroy', $allowance->id) }}" class="btn btn-danger" data-method="delete" rel="nofollow" data-confirm="Are you sure you want to delete this?" data-token="{{ csrf_token() }}">Delete</a>
                                            <a class="btn btn-warning" href="{{ URL::previous() }}">Back</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane" id="employees">
                                <span class="pull-right">
                                    <a href="{{ route('employee-allowances.create', ['allowanceId' => $allowance->id]) }}" class="btn btn-warning">Assign Employees</a>
                                    <a href="{{ route('allowances.generate', $allowance->id) }}" class="btn btn-primary">Generate Reports</a>
                                </span>
                                <h3>Employees with {{ $allowance->name }} ({{ $employees->count() }})</h3>
                                <hr>
                                <table class="table table-striped table-hover table-responsive dataTable" id="allowances_table">
                                    <thead>
                                    <tr>
                                        <th>
                                            Payroll Number
                                        </th>
                                        <th>
                                            Identification
                                        </th>
                                        <th>
                                            Full Names
                                        </th>
                                        <th>
                                            Mobile Phone
                                        </th>
                                        <th>
                                            Amount
                                        </th>
                                        <th>
                                            Edit
                                        </th>
                                        <th>
                                            Delete
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($employees as $employee)
                                        <tr>
                                            <td>
                                                <a href="{{ route('employees.show', ['id' => $employee->id]) }}">{{ $employee->payroll_number }}</a>
                                            </td>
                                            <td>
                                                {{ $employee->identification_type . ' - ' . $employee->identification_number }}
                                            </td>
                                            <td>
                                                {{ $employee->first_name . ' ' . $employee->last_name }}
                                            </td>
                                            <td>
                                                {{ $employee->mobile_phone }}
                                            </td>
                                            <td class="text-right">
                                                {{ $allowance->type == 'rate' ? $allowance->rate : number_format($allowance->employeeAllowances->keyBy('employee_id')->get($employee->id)->amount, 2) }}
                                            </td>
                                            <td>
                                                <a class="btn btn-success btn-xs" href="{{ route('employee-allowances.edit', $allowance->employeeAllowances->keyBy('employee_id')->get($employee->id)->id) }}">Edit</a>
                                            </td>
                                            <td>
                                                <a href="{{ route('employee-allowances.destroy', $allowance->employeeAllowances->keyBy('employee_id')->get($employee->id)->id) }}" class="btn btn-danger btn-xs" data-method="delete" rel="nofollow" data-confirm="Are you sure you want to delete this?" data-token="{{ csrf_token() }}">Delete</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection