routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::group(['middleware' => ['auth']], function () {
    Route::get('/', ['as' => 'dashboard', 'uses' => 'PagesController@dashboard']);
//    Route::get('logout', ['as' => 'logout', 'uses' => 'Authentication\AuthController@logout']);
    Route::get('user-profile', ['as' => 'user.profile', 'uses' => 'UsersController@profile']);
    Route::post('user-profile', ['as' => 'user.profile.update', 'uses' => 'UsersController@postProfile']);
    Route::resource('profile', 'CompanyProfileController');
    Route::resource('departments', 'DepartmentsController');
    Route::get('department-print/{department}', ['as' => 'departments.generate', 'uses' => 'DepartmentsController@generate']);
    Route::post('department-print', ['as' => 'departments.pdfs', 'uses' => 'DepartmentsController@getPDF']);
    Route::resource('allowances', 'AllowancesController');
    Route::resource('employee-allowances', 'EmployeeAllowancesController');
    Route::get('allowances-print/{id}', ['as' => 'allowances.generate', 'uses' => 'AllowancesController@generate']);
    Route::post('allowances-print', ['as' => 'allowances.document', 'uses' => 'AllowancesController@getDocument']);
    Route::resource('deductions', 'DeductionsController');
    Route::resource('employee-deductions', 'EmployeeDeductionsController');
    Route::get('deductions-report/{id}', ['as' => 'deductions.report', 'uses' => 'DeductionsController@report']);
    Route::post('deductions-print/{id}', ['as' => 'deductions.generate', 'uses' => 'DeductionsController@generate']);
    Route::post('deductions-print', ['as' => 'deductions.document', 'uses' => 'DeductionsController@getDocument']);
    Route::resource('reliefs', 'ReliefController');
    Route::resource('employee-types', 'EmployeeTypesController');
    Route::resource('payment-methods', 'PaymentMethodsController');
    Route::resource('payment-structures', 'PaymentStructureController');
    Route::resource('shifts', 'ShiftsController');
    Route::resource('work-plans', 'WorkPlanController');
    Route::resource('grades', 'PayGradesController');
    Route::resource('holidays', 'HolidaysController');
    Route::resource('employees', 'EmployeesController');
    Route::resource('contracts', 'EmployeeContractsController');
    Route::resource('assignments', 'EmployeeAssignmentsController');
    Route::resource('employee-payment-methods', 'EmployeePaymentMethodsController');
    Route::resource('payroll', 'PayrollController');
    Route::get('finalize-payroll', 'PayrollController@finalize');
    Route::get('delete-payroll', 'PayrollController@deletePayrolls');
    Route::get('payroll-pdf/{id}', ['as' => 'payroll.pdf', 'uses' => 'PayrollController@getPDF']);
    Route::get('payroll-pdfs', ['as' => 'payroll.pdfs', 'uses' => 'PayrollController@getAllPDFs']);
    Route::get('payroll-view/{month}', ['as' => 'payroll.show.all', 'uses' => 'PayrollController@viewAll']);
    Route::get('payroll-report', ['as' => 'payroll.report', 'uses' => 'PayrollController@report']);
    Route::post('payroll-generate', ['as' => 'payroll.generate', 'uses' => 'PayrollController@generate']);
    Route::post('payroll-print', ['as' => 'payroll.document', 'uses' => 'PayrollController@getDocument']);
    Route::resource('advances', 'AdvancesController');
    Route::get('advances-bulk', ['as' => 'advances.bulk', 'uses' => 'AdvancesController@bulkAssign']);
    Route::post('advances-bulk', ['as' => 'advances.process', 'uses' => 'AdvancesController@bulkProcess']);
    Route::get('loans/details/{loanId}', ['as' => 'loans.details', 'uses' => 'LoansController@details']);
    Route::resource('loans', 'LoansController');
    Route::resource('policies', 'PoliciesController');
//    Route::resource('tax', 'TaxReportsController');
    Route::get('tax', ['as' => 'tax.index', 'uses' => 'TaxReportsController@index']);
    Route::get('tax-report', 'TaxReportsController@getYear');
    Route::post('tax/{type}', ['as' => 'tax.show', 'uses' => 'TaxReportsController@getReport']);
    Route::resource('template', 'ReportTemplateController');
    Route::resource('worked', 'DaysWorkedController');
    Route::resource('hours-worked', 'HoursWorkedController');
    Route::resource('units-made', 'UnitsMadeController');
    Route::resource('coinage', 'CoinageController');
    Route::resource('users', 'UsersController');
    Route::resource('api', 'APIController');
    Route::get('allowance-report', 'ReportsController@allowances')->name('allowance-report');
});

//
//Route::get('login', ['as' => 'login.index', 'uses' => 'Auth\LoginController@getLogin']);
//Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@getLogin']);
//
//Route::post('login', ['as' => 'login.store', 'uses' => 'Auth\LoginController@postLogin']);
//Route::get('forgot', ['as' => 'forgot.index', 'uses' => 'Auth\LoginController@index']);
//Route::post('forgot', ['as' => 'forgot.store', 'uses' => 'Auth\LoginController@index']);


// Route::post('login', 'Auth\LoginController@login')->middleware('throttle:5,1');

app/Http/Controllers/API/EmployeeController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Payroll\Models\Employee;
use Response;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function index()
    {
        $pagination = request('paginate') ?: 30;
        $employees = Employee::when(request('departments'), function ($builder) {
            return $builder->join('assignments', 'assignments.employee_id', '=', 'employees.id')
                ->join('departments', 'assignments.department_id', '=', 'departments.id')
                ->whereIn('departments.id', explode(',', request('departments')))
                ->select([
                    'employees.id', 'departments.id as department_id', 'payroll_number', 'avatar',
                    'identification_number', 'identification_type', 'first_name', 'last_name', 'email', 'mobile_phone',
                    'has_custom_tax_rate', 'custom_tax_rate'
                ]);
        })
            ->paginate(intval($pagination));

        return Response::json($employees);
    }
}

app/Http/Controllers/EmployeesController.php
<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use App\Policies\Policy;
use Illuminate\Http\Request;
use Payroll\Models\Employee;
use Payroll\Models\PayGrade;
use Payroll\Models\Allowance;
use Payroll\Models\Deduction;
use Payroll\Models\Assignment;
use Payroll\Models\Department;
use Payroll\Models\EmployeeType;
use Payroll\Models\PaymentMethod;
use Payroll\Models\EmployeeContract;
use Payroll\Models\EmployeeAllowance;
use Payroll\Models\EmployeeDeduction;
use Payroll\Models\EmployeePaymentMethods;

class EmployeesController extends Controller
{
    /**
     * @var Employee
     */
    private $employee;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Policy::canRead(new Employee);

        return view('modules.employees.enrol.index')
            ->withEmployees(Employee::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        Policy::canCreate(new Employee());
        return view('modules.employees.enrol.create')
            ->withEmployeeType(EmployeeType::all())
            ->withPayGrades(PayGrade::all())
            ->withDepartments(Department::all())
            ->withEmployees(Employee::all())
            ->withPaymentMethods(PaymentMethod::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Policy::canCreate(new Employee());

        $request['payroll_number'] = generatePayrollNumber(auth()->user()->id);

        $data = $request->all();
        $data['start_date'] = Carbon::parse($data['start_date']);
        $data['end_date'] = Carbon::parse($data['end_date']);
        $data['times_renewed'] = 0;
        $data['has_custom_tax_rate'] = $request->has('has_custom_tax_rate');
        $data['custom_tax_rate'] = $data['has_custom_tax_rate'] ? $data['custom_tax_rate'] : 0;
        $employee = Employee::create($data);
        $data['employee_id'] = $employee->id;
        $now = Carbon::now();


        EmployeeContract::create($data);

        if ($request->has('allowances')) {
            $allowances = array();

            foreach ($data['allowances'] as $allowance) {
                $allowances [] = [
                    'employee_id' => $employee->id,
                    'allowance_id' => $allowance,
                    'currency_id' => $data['currency_id'],
                    'amount' => isset($data['allowance' . $allowance . '_amount']) ? $data['allowance' . $allowance . '_amount'] : 0,
                    'created_at' => $now,
                    'updated_at' => $now
                ];
            }

            EmployeeAllowance::insert($allowances);
        }

        if ($request->has('deductions')) {
            $deductions = array();

            foreach ($data['deductions'] as $deduction) {
                $deduct = [
                    'employee_id' => $employee->id,
                    'deduction_id' => $deduction,
                    'deduction_number' => $data['deduction' . $deduction . '_number'],
                    'amount' => null,
                    'created_at' => $now,
                    'updated_at' => $now
                ];

                if (in_array('deduction' . $deduction . '_deduction_amount', array_keys($data))) {
                    $deduct['amount'] = $data['deduction' . $deduction . '_deduction_amount'];
                }

                $deductions [] = $deduct;
            }
            EmployeeDeduction::insert($deductions);
        }

        $payment = EmployeePaymentMethods::create([
            'employee_id' => $data['employee_id'],
            'payment_method_id' => $data['payment_method_id'],
            // account-number
            // bank-name
            // branch-name
            // phone-number
        ]);

        $method = PaymentMethod::with('udfs')->findOrFail($data['payment_method_id']);
        $payment->updateWithUdfs($method->udfs, $data);
        $payment->save();

        Assignment::create([
            'employee_id' => $employee->id,
            'department_id' => $data['department_id']
        ]);

        flash('Successfully added new employee', 'success');

        return redirect()->route('employees.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        Policy::canRead(new Employee());
        $employee = Employee::with([
            'contract', 'paymentMethod', 'deductions', 'allowances', 'advances', 'advancePayments', 'deductionPayments'
        ])->findOrFail($id);
        $deductions = Deduction::all()->keyBy('id');
        $allowances = Allowance::all()->keyBy('id');
        $paymentMethod = PaymentMethod::with(['udfs'])->find($employee->paymentMethod->payment_method_id);

        return view('modules.employees.enrol.show')
            ->withPaymentMethod($paymentMethod)
            ->withEmployee($employee)
            ->withDeductions($deductions)
            ->withAllowances($allowances);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        Policy::canUpdate(new Employee());
        $employee = Employee::findOrFail($id);

        return view('modules.employees.enrol.edit')
            ->withEmployeeType(EmployeeType::all())
            ->withPayGrades(PayGrade::all())
            ->withDepartments(Department::all())
            ->withEmployees(Employee::all())
            ->withPaymentMethods(PaymentMethod::all())
            ->withInput($employee);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int                      $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Policy::canUpdate(new Employee());
        $employee = Employee::findOrFail($id);
        $data = $request->all();
        $data['has_custom_tax_rate'] = $request->has('has_custom_tax_rate');

        $employee->fill($data);
        $employee->save();
        flash('Successfully updated employee record.', 'success');

        return redirect()->route('employees.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Policy::canDelete(new Employee());

        $employee = Employee::findOrFail($id);
        $employee->contract()->forceDelete();
        $employee->advances()->delete();
        $employee->deductionPayments()->delete();
        $employee->allowances()->delete();
        $employee->advancePayments()->delete();
        $employee->deductions()->delete();
        $employee->assignment()->delete();
        $employee->p9()->delete();
        $employee->loans()->delete();
        $employee->hoursWorked()->delete();
        $employee->unitsMade()->delete();
        $employee->daysWorked()->delete();
        $employee->paymentMethod()->delete();
        $employee->payroll()->delete();
        $employee->delete();
        flash('Successfully deleted employee record.', 'success');

        return redirect()->route('employees.index');
    }
}

resources/views/modules/employees/contracts/index.blade.php
@extends('layout')

@section('content')
    <div class="page-head">
        <div class="page-title">
            <h1>Employee Contracts - <small> The current contracts that the organization has.</small></h1>
        </div>
    </div>
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="{{ url('/') }}">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="{{ route('contracts.index') }}">Employee Contracts</a>
        </li>
    </ul>

    <div class="row">
        <div class="col-sm-12">
            <!-- BEGIN PORTLET-->
            <div class="portlet light ">
                <div class="portlet-title">
                    <div class="caption caption-md">
                        <i class="icon-bar-chart theme-font-color hide"></i>
                        <span class="caption-subject theme-font-color bold uppercase">Current Employee Types</span>
                    </div>
                    <div class="actions">
                        <a href="{{ route('contracts.create') }}" class="btn btn-transparent grey-salsa btn-circle btn-sm active"><i class="fa fa-plus"></i> Add New Contract</a>
                    </div>
                </div>
                <div class="portlet-body">
                    <table class="table table-striped table-hover table-responsive dataTable" id="allowances_table">
                        <thead>
                            <tr>
                                <th>
                                    Employee
                                </th>
                                <th>
                                    Employee Type
                                </th>
                                <th>
                                    Pay Grade
                                </th>
                                <th>
                                    Contract Start
                                </th>
                                <th>
                                    Contract End
                                </th>
                                <th>
                                    View
                                </th>
                                <th>
                                    Edit
                                </th>
                                <th>
                                    Delete
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($contracts as $contract)
                            <tr>
                                <td>
                                    <a href="{{ route('employees.show', $contract->employee->id) }}">{{ $contract->employee->first_name . ' ' . $contract->employee->last_name }}</a>
                                </td>
                                <td class="text-center">
                                    <a href="{{ route('employee-types.show', $contract->employeeType->id) }}">{{ $contract->employeeType->name }}</a>
                                </td>
                                <td class="text-center">
                                    <a href="{{ route('grades.show', $contract->payGrade->id) }}">{{ $contract->payGrade->name }}</a>
                                </td>
                                <td class="text-center">
                                    {{ $contract->start_date->toFormattedDateString() }}
                                </td>
                                <td class="text-center">
                                    {{ $contract->end_date->toFormattedDateString() }}
                                </td>
                                <td class="text-center">
                                    <a class="btn btn-primary btn-xs" href="{{ route('contracts.show', $contract->id) }}">
                                        View </a>
                                </td>
                                <td class="text-center">
                                    <a class="btn btn-success btn-xs" href="{{ route('contracts.edit', $contract->id) }}">
                                        Edit </a>
                                </td>
                                <td class="text-center">
                                    <a href="{{ route('contracts.destroy', $contract->id) }}" class="btn btn-danger btn-xs" data-method="delete" rel="nofollow" data-confirm="Are you sure you want to delete this?" data-token="{{ csrf_token() }}">Delete</a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END PORTLET-->
        </div>
    </div>

@endsection

resources/views/modules/employees/contracts/show.blade.php
@extends('layout')
@section('content')
    <div class="page-head">
        <div class="page-title">
            <h1>Employee Contracts - <small> The current contracts that the organization has.</small></h1>
        </div>
    </div>
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="{{ url('/') }}">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="{{ route('contracts.index') }}">Employee Contracts</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="#">View</a>
        </li>
    </ul>

    <div class="row">
        <div class="col-sm-12">
                <div class="portlet light">
                    <div class="portlet-title">
                        <div class="caption font-red-sunglo">
                            <i class="fa fa-briefcase font-red-sunglo"></i>
                            <span class="caption-subject bold uppercase"> Employee Contract Details</span>
                        </div>
                    </div>
                    <div class="portlet-body form">
                        <div class="form-body row">
                            <div class="col-sm-6">
                                <div class="form-group form-md-line-input form-md-floating-label">
                                    <label for="name">Employee Name</label>
                                    <div class="form-control">
                                        <a href="{{ route('employees.show', $contract->employee->id) }}">{{ $contract->employee->first_name . ' ' . $contract->employee->last_name }}</a>
                                    </div>
                                </div>
                                <div class="form-group form-md-line-input form-md-floating-label">
                                    <label for="name">Employee Type</label>
                                    <div class="form-control">
                                        <a href="{{ route('employee-types.show', $contract->employeeType->id) }}">{{ $contract->employeeType->name }}</a>
                                    </div>
                                </div>
                                <div class="form-group form-md-line-input form-md-floating-label">
                                    <label for="name">Pay Grade</label>
                                    <div class="form-control">
                                        <a href="{{ route('grades.show', $contract->payGrade->id) }}">{{ $contract->payGrade->name }}</a>
                                    </div>
                                </div>
                                <div class="form-group form-md-line-input form-md-floating-label">
                                    <a class="btn btn-success" href="{{ route('contracts.edit', $contract->id) }}">Edit</a>
                                    <a href="{{ route('contracts.destroy', $contract->id) }}" class="btn btn-danger" data-method="delete" rel="nofollow" data-confirm="Are you sure you want to delete this?" data-token="{{ csrf_token() }}">Delete</a>
                                    <a class="btn btn-warning" href="{{ route('contracts.index') }}">Back</a>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group form-md-line-input form-md-floating-label">
                                    <label for="name">Current Basic Salary</label>
                                    <div class="form-control">
                                        {{ $contract->currency->code . ' ' . number_format($contract->current_basic_salary, 2) }}
                                    </div>
                                </div>
                                <div class="form-group form-md-line-input form-md-floating-label">
                                    <label for="name">Contract Start Date</label>
                                    <div class="form-control">
                                        {{ $contract->start_date->toFormattedDateString() }}
                                    </div>
                                </div>
                                <div class="form-group form-md-line-input form-md-floating-label">
                                    <label for="name">Contract End Date</label>
                                    <div class="form-control">
                                        {{ $contract->end_date->toFormattedDateString() }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    </div>
@endsection